#! /bin/sh
base=`dirname "$0"`
command="$1"
robo="$base/vendor-bin/robo/vendor/bin/robo"
if [ -z "$ARSSE_PHP" ]; then
    php="php"
else
    php="$ARSSE_PHP"
fi

if [ $# -eq 0 ]; then
    "$php" "$robo"
else
    shift
    ulimit -n 2048
    "$php" "$robo" "$command" -- "$@"
fi
