#! /bin/sh
base=`dirname "$0"`
roboCommand="$1"
if [ $# -eq 0 ]; then
    "$base/vendor/bin/robo"
else
    shift
    ulimit -n 2048
    if [ "$1" = "clean" ]; then
        "$base/vendor/bin/robo" "$roboCommand" "$@"
    else
        "$base/vendor/bin/robo" "$roboCommand" -- "$@"
    fi
fi
