#! /bin/sh
base=`dirname "$0"`
php -S localhost:8000 "$base/server.php"  >/dev/null &
php "$base/../vendor/phpunit/phpunit/phpunit" -c "$base/phpunit.xml"
sleep 1s
pid=`netstat -tlpn 2>/dev/null | grep ":8000 " | grep -Eo "[0-9]+/php" | grep -Eo "[0-9]+"`
kill $pid