#!/bin/bash
function err() {
    echo "TARBALL: $1" >&2
    cleanup
    exit 1
}
function cleanup() {
    if [ -n "$tmp_dir" ]; then
        rm -rf "$tmp_dir"
        git -C "$prj_dir" worktree prune
    fi
}
function replace() {
    if [ "$(sed --version | grep -c '^sed (GNU sed) ')" == 1 ]; then
        sed -i -e "$2" "$1"
    else
        sed -i '' -e "$2" "$1"
    fi
}

for tool in git tar php composer; do
    if [ ! "$(command -v $tool)" ]; then
        err "The $tool command is required for this script to function"
    fi
done
if [ -z "$1" ]; then
    echo "Usage: $0 <git-commit-ish>"
    echo ""
    echo "The <git-commit-ish> argument may be any valid Git commit-ish"
    echo "reference. For more details see the Git documentation here:"
    echo "https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-commit-ishalsocommittish"
    exit 1
fi

prj_dir="$(dirname $(dirname "$0"))"
# validate the commit
commit="$1"
version="$(git -C "$prj_dir" describe --tags "$commit" 2>/dev/null)"
if [ -z "$version"]; then
    err "The supplied Git commit-ish is invalid"
fi
$tarball = "$prj_dir/release/$version/arsse-$version.tar.gz"
# create a temporary worktree
tmp_dir="$(mktemp -d)"
wrk_dir="$tmp_dir/arsse"
mkdir -p "$wrk_dir"
git -C "$prj_dir" worktree add "$wrk_dir" "$commit"
if [ "$?" -gt 0 ];
    err "Unable to create temporary Git worktree"
fi
# fix up the Arch PKGBUILD, if there is one
if [ -f "$wrk_dir/dist/arch/PKGBUILD" ]; then
    archVersion="$(sed -e 's/^\([^-]\+\)-\([0-9]\+\)-\(.\+\)/\1.r\2.\3/' <<< "$version")"
    replace "$wrk_dir/dist/arch/PKGBUILD" 's/^pkgver=.\+/pkgver='"$archVersion"'/'
    replace "$wrk_dir/dist/arch/PKGBUILD" 's/^source=("arsse-[^"]\+")$/source=("'"$(basename "$tarball")"'")/'
fi
# write the Debian changelog, if appropriate
if [ -f "$wrk_dir/dist/debian/control" ]; then
    "$prj_dir/scripts/changelog" "$version" debian > "$wrk_dir/dist/debain/changelog"
fi
# fix up the RPM specfile, if appropriate (this isn't well tested)
if [ -f "$wrk_dir/dist/rpm/arsse.spec" ]; then
    baseVersion="$(sed -e 's/^\([^-]\+\).*/\1/' <<< "$version")"
    release="$(sed -e 's/^\([^-]\+\)-\([0-9]\+\).*/\2/' <<< "$version")"
    replace "$wrk_dir/dist/rpm/arsse.spec" 's/^\(Version:        \).*$/\1'"$baseVersion"'/'
    replace "$wrk_dir/dist/rpm/arsse.spec" 's/^\(Release:        \).*$/\1'"$release"'/'
    replace "$wrk_dir/dist/rpm/arsse.spec" 's/^\(Source0:        \).*$/\1'"$(basename "$tarball")"'/'
    "$prj_dir/scripts/changelog" "$version" rpm >> "$wrk_dir/dist/rpm/arsse.spec"
fi
# save commit description to VERSION file for reference
echo -n "$version" > "$wrk_dir/VERSION"
# if an HTML manual and/or Markdown-formatted Unix manual is included (this is true for any release since 0.8.1) retrieve development tooling
if [ -f "$wrk_dir/docs/index.md" -o -f "$wrk_dir/manpages/en.md" ]; then
    pushd "$wrk_dir" >/dev/null
    composer install -q
    # if this version was still using Robo, use Robo
    if [ -f "$wrk_dir/robo.bat" ]; then
        ./robo manual -q
        # If a Markdown-formatted Unix manual still exists (only true between 0.10.0 and 0.10.4) convert it
        if [ -f "$wrk_dir/manpages/en.md" ]; then
            ./robo manpage
        fi
    else
        # otherwise use Composer to generate the HTML manual
        composer manual
    fi
    popd >/dev/null
fi
# install runtime dependencies 
composer -d "$wrk_dir" install -o --no-dev --no-scripts -q
# remove unnecessary files
for f in .git .gitignore .gitattributes dist/debian/.gitignore composer.json composer.lock .php_cs.dist .php-cs-fixer.dist.php phpdoc.dist.xml build.xml RoboFile.php CONTRIBUTING.md docs manpages tests vendor-bin vendor/bin robo robo.bat package.json yarn.lock postcss.config.js; do
    rm -rf "$wrk_dir/$f"
done
for d in "$tmpp_dir"/*/*; do
    for f in .git .github .phan test tests examples scripts vendor-bin .editorconfig .gitignore .gitattributes .gitmodules .php-cs-fixer.dist.php .php_cs.dist .travis.yml composer.json composer.lock docker-compose.yaml picofeed phpunit.xml psalm.xml.dist robo robo.bat RoboFile.php test.php; do
        rm -rf "$d/$f"
    done
done
# generate a sample configuration file
php "$wrk_dir/arsse.php" conf save-defaults "$wrk_dir/config.defaults.php"
# remove any existing tarball
rm -f "$tarball"
# package it all up and clean up
GZIP=-9 tar czf "$tarball" "$wrk_dir"
cleanup
