#!/uyser/bin/env php
<?php

$debianDir = $argv[1] ?? "";
$version = $argv[2] ?? "";
$tarballs = array_slice($argv, 3);
if (!preg_match('/^\d+\.\d+\.\d+(?:-\d+)?$/', $version) || !is_dir($debianDir) || !sizeof($tarballs)) {
    echo <<<INFO
Usage: changelog <debian_dir> <version> <tarball>...

The <debian_dir> argument should point to a directory where a Debian control
file and other Debian files exist. The <version> argument is a Debian-format
version string of the type x.y.z-a. Finally one or more <tarball> arguments
refer to the actual package data.

INFO;
    exit(1);
}

try {
    echo trim(generateDebianSourceControl($debianDir, $version, $tarballs))."\n";
} catch (\Exception $e) {
    fwrite(\STDERR, "DSC: ".$e->getMessage()."\n");
    exit(2);
}

/** Produces a Debian "source control" file from various bits of data
 *
 * As with a Debian changelog, the output is of a very exacting format,
 * and this function should be modified with care.
 *
 * @param string $dir The path to Debian-specific files
 * @param string $version The Debian version string, in the format x.y.z-a
 * @param array $tarballs An array of paths to the "orig" and "debian" tarball files
 */
function generateDebianSourceControl(string $dir, string $version, array $tarballs): string {
    // read in control file
    if (!$control = @file_get_contents($dir."/control")) {
        throw new \Exception("Unable to read Debian control file");
    }
    // read the format
    if (!$format = @file_get_contents($dir."/source/format")) {
        throw new \Exception("Unable to read source format in Debian files");
    }
    // read the binary packages from the control file
    if (preg_match_all('/^Package:\s*(\S+)/m', $control, $m)) {
        $binary = [];
        foreach ($m[1] as $pkg) {
            $binary[] = $pkg;
        }
    } else {
        throw new \Exception("No packages defined in Debian control file");
    }
    // read the package architectures from the control file
    if (preg_match_all('/^Architecture:\s*(\S+)/m', $control, $m) || sizeof($m[1]) != sizeof($binary)) {
        $architecture = [];
        foreach ($m[1] as $pkg) {
            $architecture[] = preg_replace('/\s/', "", $pkg);
        }
    } else {
        throw new \Exception("Number of architectures defined in Debian control file does not match number of packages");
    }
    // read the package sections from the control file
    if (preg_match_all('/^Section:\s*(\S+)/m', $control, $m) || sizeof($m[1]) != sizeof($binary)) {
        $section = [];
        foreach ($m[1] as $pkg) {
            $section[] = $pkg;
        }
    } else {
        throw new \Exception("Number of sections defined in Debian control file does not match number of packages");
    }
    // read the package priorities from the control file
    if (preg_match_all('/^Priority:\s*(\S+)/m', $control, $m) || sizeof($m[1]) != sizeof($binary)) {
        $priority = [];
        foreach ($m[1] as $pkg) {
            $priority[] = $pkg;
        }
    } else {
        throw new \Exception("Number of priorities defined in Debian control file does not match number of packages");
    }
    // read simple metadata from the control file
    $metadata = [];
    foreach (["Source", "Maintainer", "Homepage", "Standards-Version", "Vcs-Browser", "Vcs-Git"] as $meta) {
        if (preg_match('/^'.$meta.':\s*(.+)/m', $control, $m)) {
            $metadata[$meta] = $m[1];
        } else {
            throw new \Exception("$meta is not defined in Debian control file");
        }
    }
    // read build dependencies from control file
    if (preg_match('/(?:^|\n)Build-Depends:\s*((?:[^\n]|\n(?= ))+)/s', $control, $m)) {
        $buildDepends = preg_replace('/\s/', "", $m[1]);
    } else {
        $buildDepends = "";
    }
    // trim format
    $format = trim($format);
    // consolidate binaries and package list
    $packageList = [];
    for ($a = 0; $a < sizeof($binary); $a++) {
        $packageList[] = "$binary[$a] deb $section[$a] $priority[$a] arch=$architecture[$a]";
    }
    $packageList = implode("\n ", $packageList);
    // consolidate package names
    $binary = implode(",", $binary);
    // consolidate architectures
    $architecture = implode(",", array_unique($architecture));
    // calculate checksums for files
    $fMeta = [];
    foreach ($tarballs as $f) {
        $fMeta[$f] = [
            'name'   => basename($f),
            'size'   => filesize($f),
            'sha1'   => hash_file("sha1", $f),
            'sha256' => hash_file("sha256", $f),
            'md5'    => hash_file("md5", $f),
        ];
    }
    // consolidate SHA-1 checksums
    $sums = [];
    foreach ($fMeta as $data) {
        $sums[] = $data['sha1']." ".$data['size']." ".$data['name'];
    }
    $sumsSha1 = implode("\n ", $sums);
    // consolidate SHA-256 checksums
    $sums = [];
    foreach ($fMeta as $data) {
        $sums[] = $data['sha256']." ".$data['size']." ".$data['name'];
    }
    $sumsSha256 = implode("\n ", $sums);
    // consolidate MD5 checksums
    $sums = [];
    foreach ($fMeta as $data) {
        $sums[] = $data['md5']." ".$data['size']." ".$data['name'];
    }
    $sumsMd5 = implode("\n ", $sums);
    // return complete file
    return <<< DSC_FILE
Format: $format
Source: {$metadata['Source']}
Binary: $binary
Architecture: $architecture
Version: $version
Maintainer: {$metadata['Maintainer']}
Homepage: {$metadata['Homepage']}
Standards-Version: {$metadata['Standards-Version']}
Vcs-Browser: {$metadata['Vcs-Browser']}
Vcs-Git: {$metadata['Vcs-Git']}
Build-Depends: $buildDepends
Package-List:
 $packageList
Checksums-Sha1:
 $sumsSha1
Checksums-Sha256:
 $sumsSha256
Files:
 $sumsMd5

DSC_FILE;
}
